### ISSUE TITLE
Update Stamen tiles URLs

### ISSUE THREAD

**Issue by ebrelsford** [Zverik/openwhatevermap#6]
Stamen tiles are moving to Stadia as announced [here](http://maps.stamen.com/stadia-partnership/).

openwhatevermap should be able to continue using the tiles by:
 1. [Creating a Stadia account](https://stadiamaps.com/stamen/onboarding/create-account/) and
 2. Updating tile URL templates as specified in [the docs](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/)

Happy to help with this if that would be helpful.

**Comment by Zverik** [comment]
Done, thanks for the reminder.

**Comment by ianthetechie** [comment]
Hey @Zverik, not to necro the issue, but just I noticed you added the retina placeholder for watercolor. Unfortunately the watercolor tiles don't support HiDPI so those are currently blank squares.

**Comment by Zverik** [comment]
Good catch, thanks Ian!
